spring.jpa:
    show-sql: true
    database: MYSQL
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shirodemo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 10088

spring:
  output:
    ansi:
      enabled: ALWAYS

auth.loginUrl: /login #登录链接
auth.unauthorizedUrl: /403 #没有权限跳转链接
auth.filterString: /logout=logout;/403=anon;/helloWorld=anon;/**=authc  #过滤器配置,/**写在最后